export const types = {
    FETCH_REPOSITORIES: 'FETCH_REPOSITORIES',
    FETCH_REPOSITORY: 'FETCH_REPOSITORY',
    CREATE_REPOSITORY: 'CREATE_REPOSITORY',
    UPDATE_REPOSITORY: 'UPDATE_REPOSITORY',
    DELETE_REPOSITORY: 'DELETE_REPOSITORY',
    UPDATE_STATE: 'UPDATE_STATE',
    EXPORT_REPOSITORY: 'EXPORT_REPOSITORY',
    EXPORT_TEMPLATE: 'EXPORT_TEMPLATE'
};